// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/scutrobotlab/HR/dal/model"
)

func newIntent(db *gorm.DB) intent {
	_intent := intent{}

	_intent.intentDo.UseDB(db)
	_intent.intentDo.UseModel(&model.Intent{})

	tableName := _intent.intentDo.TableName()
	_intent.ALL = field.NewField(tableName, "*")
	_intent.ID = field.NewInt32(tableName, "id")
	_intent.ApplicantID = field.NewInt32(tableName, "applicant_id")
	_intent.GroupID = field.NewInt32(tableName, "group_id")
	_intent.IntentRank = field.NewInt16(tableName, "intent_rank")

	_intent.fillFieldMap()

	return _intent
}

type intent struct {
	intentDo intentDo

	ALL         field.Field
	ID          field.Int32
	ApplicantID field.Int32
	GroupID     field.Int32
	IntentRank  field.Int16

	fieldMap map[string]field.Expr
}

func (i intent) Table(newTableName string) *intent {
	i.intentDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i intent) As(alias string) *intent {
	i.intentDo.DO = *(i.intentDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *intent) updateTableName(table string) *intent {
	i.ALL = field.NewField(table, "*")
	i.ID = field.NewInt32(table, "id")
	i.ApplicantID = field.NewInt32(table, "applicant_id")
	i.GroupID = field.NewInt32(table, "group_id")
	i.IntentRank = field.NewInt16(table, "intent_rank")

	i.fillFieldMap()

	return i
}

func (i *intent) WithContext(ctx context.Context) *intentDo { return i.intentDo.WithContext(ctx) }

func (i intent) TableName() string { return i.intentDo.TableName() }

func (i intent) Alias() string { return i.intentDo.Alias() }

func (i *intent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *intent) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 4)
	i.fieldMap["id"] = i.ID
	i.fieldMap["applicant_id"] = i.ApplicantID
	i.fieldMap["group_id"] = i.GroupID
	i.fieldMap["intent_rank"] = i.IntentRank
}

func (i intent) clone(db *gorm.DB) intent {
	i.intentDo.ReplaceDB(db)
	return i
}

type intentDo struct{ gen.DO }

func (i intentDo) Debug() *intentDo {
	return i.withDO(i.DO.Debug())
}

func (i intentDo) WithContext(ctx context.Context) *intentDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i intentDo) Clauses(conds ...clause.Expression) *intentDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i intentDo) Returning(value interface{}, columns ...string) *intentDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i intentDo) Not(conds ...gen.Condition) *intentDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i intentDo) Or(conds ...gen.Condition) *intentDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i intentDo) Select(conds ...field.Expr) *intentDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i intentDo) Where(conds ...gen.Condition) *intentDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i intentDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *intentDo {
	return i.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (i intentDo) Order(conds ...field.Expr) *intentDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i intentDo) Distinct(cols ...field.Expr) *intentDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i intentDo) Omit(cols ...field.Expr) *intentDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i intentDo) Join(table schema.Tabler, on ...field.Expr) *intentDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i intentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *intentDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i intentDo) RightJoin(table schema.Tabler, on ...field.Expr) *intentDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i intentDo) Group(cols ...field.Expr) *intentDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i intentDo) Having(conds ...gen.Condition) *intentDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i intentDo) Limit(limit int) *intentDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i intentDo) Offset(offset int) *intentDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i intentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *intentDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i intentDo) Unscoped() *intentDo {
	return i.withDO(i.DO.Unscoped())
}

func (i intentDo) Create(values ...*model.Intent) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i intentDo) CreateInBatches(values []*model.Intent, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i intentDo) Save(values ...*model.Intent) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i intentDo) First() (*model.Intent, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Intent), nil
	}
}

func (i intentDo) Take() (*model.Intent, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Intent), nil
	}
}

func (i intentDo) Last() (*model.Intent, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Intent), nil
	}
}

func (i intentDo) Find() ([]*model.Intent, error) {
	result, err := i.DO.Find()
	return result.([]*model.Intent), err
}

func (i intentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Intent, err error) {
	buf := make([]*model.Intent, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i intentDo) FindInBatches(result *[]*model.Intent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i intentDo) Attrs(attrs ...field.AssignExpr) *intentDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i intentDo) Assign(attrs ...field.AssignExpr) *intentDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i intentDo) Joins(fields ...field.RelationField) *intentDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i intentDo) Preload(fields ...field.RelationField) *intentDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i intentDo) FirstOrInit() (*model.Intent, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Intent), nil
	}
}

func (i intentDo) FirstOrCreate() (*model.Intent, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Intent), nil
	}
}

func (i intentDo) FindByPage(offset int, limit int) (result []*model.Intent, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i intentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i *intentDo) withDO(do gen.Dao) *intentDo {
	i.DO = *do.(*gen.DO)
	return i
}
