// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/scutrobotlab/HR/dal/model"
)

func newScore(db *gorm.DB) score {
	_score := score{}

	_score.scoreDo.UseDB(db)
	_score.scoreDo.UseModel(&model.Score{})

	tableName := _score.scoreDo.TableName()
	_score.ALL = field.NewField(tableName, "*")
	_score.AdminID = field.NewInt32(tableName, "admin_id")
	_score.ApplicantID = field.NewInt32(tableName, "applicant_id")
	_score.GroupID = field.NewInt32(tableName, "group_id")
	_score.Score = field.NewFloat64(tableName, "score")
	_score.StandardID = field.NewInt32(tableName, "standard_id")
	_score.EvaluationDetails = field.NewString(tableName, "evaluation_details")
	_score.UpdatedAt = field.NewTime(tableName, "updated_at")

	_score.fillFieldMap()

	return _score
}

type score struct {
	scoreDo scoreDo

	ALL               field.Field
	AdminID           field.Int32
	ApplicantID       field.Int32
	GroupID           field.Int32
	Score             field.Float64
	StandardID        field.Int32
	EvaluationDetails field.String
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (s score) Table(newTableName string) *score {
	s.scoreDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s score) As(alias string) *score {
	s.scoreDo.DO = *(s.scoreDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *score) updateTableName(table string) *score {
	s.ALL = field.NewField(table, "*")
	s.AdminID = field.NewInt32(table, "admin_id")
	s.ApplicantID = field.NewInt32(table, "applicant_id")
	s.GroupID = field.NewInt32(table, "group_id")
	s.Score = field.NewFloat64(table, "score")
	s.StandardID = field.NewInt32(table, "standard_id")
	s.EvaluationDetails = field.NewString(table, "evaluation_details")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *score) WithContext(ctx context.Context) *scoreDo { return s.scoreDo.WithContext(ctx) }

func (s score) TableName() string { return s.scoreDo.TableName() }

func (s score) Alias() string { return s.scoreDo.Alias() }

func (s *score) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *score) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["admin_id"] = s.AdminID
	s.fieldMap["applicant_id"] = s.ApplicantID
	s.fieldMap["group_id"] = s.GroupID
	s.fieldMap["score"] = s.Score
	s.fieldMap["standard_id"] = s.StandardID
	s.fieldMap["evaluation_details"] = s.EvaluationDetails
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s score) clone(db *gorm.DB) score {
	s.scoreDo.ReplaceDB(db)
	return s
}

type scoreDo struct{ gen.DO }

func (s scoreDo) Debug() *scoreDo {
	return s.withDO(s.DO.Debug())
}

func (s scoreDo) WithContext(ctx context.Context) *scoreDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s scoreDo) Clauses(conds ...clause.Expression) *scoreDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s scoreDo) Returning(value interface{}, columns ...string) *scoreDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s scoreDo) Not(conds ...gen.Condition) *scoreDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s scoreDo) Or(conds ...gen.Condition) *scoreDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s scoreDo) Select(conds ...field.Expr) *scoreDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s scoreDo) Where(conds ...gen.Condition) *scoreDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s scoreDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *scoreDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s scoreDo) Order(conds ...field.Expr) *scoreDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s scoreDo) Distinct(cols ...field.Expr) *scoreDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s scoreDo) Omit(cols ...field.Expr) *scoreDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s scoreDo) Join(table schema.Tabler, on ...field.Expr) *scoreDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s scoreDo) LeftJoin(table schema.Tabler, on ...field.Expr) *scoreDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s scoreDo) RightJoin(table schema.Tabler, on ...field.Expr) *scoreDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s scoreDo) Group(cols ...field.Expr) *scoreDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s scoreDo) Having(conds ...gen.Condition) *scoreDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s scoreDo) Limit(limit int) *scoreDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s scoreDo) Offset(offset int) *scoreDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s scoreDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *scoreDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s scoreDo) Unscoped() *scoreDo {
	return s.withDO(s.DO.Unscoped())
}

func (s scoreDo) Create(values ...*model.Score) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s scoreDo) CreateInBatches(values []*model.Score, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s scoreDo) Save(values ...*model.Score) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s scoreDo) First() (*model.Score, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Score), nil
	}
}

func (s scoreDo) Take() (*model.Score, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Score), nil
	}
}

func (s scoreDo) Last() (*model.Score, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Score), nil
	}
}

func (s scoreDo) Find() ([]*model.Score, error) {
	result, err := s.DO.Find()
	return result.([]*model.Score), err
}

func (s scoreDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Score, err error) {
	buf := make([]*model.Score, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s scoreDo) FindInBatches(result *[]*model.Score, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s scoreDo) Attrs(attrs ...field.AssignExpr) *scoreDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s scoreDo) Assign(attrs ...field.AssignExpr) *scoreDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s scoreDo) Joins(fields ...field.RelationField) *scoreDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s scoreDo) Preload(fields ...field.RelationField) *scoreDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s scoreDo) FirstOrInit() (*model.Score, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Score), nil
	}
}

func (s scoreDo) FirstOrCreate() (*model.Score, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Score), nil
	}
}

func (s scoreDo) FindByPage(offset int, limit int) (result []*model.Score, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s scoreDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s *scoreDo) withDO(do gen.Dao) *scoreDo {
	s.DO = *do.(*gen.DO)
	return s
}
