// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/scutrobotlab/HR/dal/model"
)

func newStandard(db *gorm.DB) standard {
	_standard := standard{}

	_standard.standardDo.UseDB(db)
	_standard.standardDo.UseModel(&model.Standard{})

	tableName := _standard.standardDo.TableName()
	_standard.ALL = field.NewField(tableName, "*")
	_standard.ID = field.NewUint(tableName, "id")
	_standard.CreatedAt = field.NewTime(tableName, "created_at")
	_standard.UpdatedAt = field.NewTime(tableName, "updated_at")
	_standard.DeletedAt = field.NewField(tableName, "deleted_at")
	_standard.Name = field.NewString(tableName, "name")
	_standard.Content = field.NewString(tableName, "content")
	_standard.AdminID = field.NewInt32(tableName, "admin_id")

	_standard.fillFieldMap()

	return _standard
}

type standard struct {
	standardDo standardDo

	ALL       field.Field
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Name      field.String
	Content   field.String
	AdminID   field.Int32

	fieldMap map[string]field.Expr
}

func (s standard) Table(newTableName string) *standard {
	s.standardDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s standard) As(alias string) *standard {
	s.standardDo.DO = *(s.standardDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *standard) updateTableName(table string) *standard {
	s.ALL = field.NewField(table, "*")
	s.ID = field.NewUint(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.Name = field.NewString(table, "name")
	s.Content = field.NewString(table, "content")
	s.AdminID = field.NewInt32(table, "admin_id")

	s.fillFieldMap()

	return s
}

func (s *standard) WithContext(ctx context.Context) *standardDo { return s.standardDo.WithContext(ctx) }

func (s standard) TableName() string { return s.standardDo.TableName() }

func (s standard) Alias() string { return s.standardDo.Alias() }

func (s *standard) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *standard) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["name"] = s.Name
	s.fieldMap["content"] = s.Content
	s.fieldMap["admin_id"] = s.AdminID
}

func (s standard) clone(db *gorm.DB) standard {
	s.standardDo.ReplaceDB(db)
	return s
}

type standardDo struct{ gen.DO }

func (s standardDo) Debug() *standardDo {
	return s.withDO(s.DO.Debug())
}

func (s standardDo) WithContext(ctx context.Context) *standardDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s standardDo) Clauses(conds ...clause.Expression) *standardDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s standardDo) Returning(value interface{}, columns ...string) *standardDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s standardDo) Not(conds ...gen.Condition) *standardDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s standardDo) Or(conds ...gen.Condition) *standardDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s standardDo) Select(conds ...field.Expr) *standardDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s standardDo) Where(conds ...gen.Condition) *standardDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s standardDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *standardDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s standardDo) Order(conds ...field.Expr) *standardDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s standardDo) Distinct(cols ...field.Expr) *standardDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s standardDo) Omit(cols ...field.Expr) *standardDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s standardDo) Join(table schema.Tabler, on ...field.Expr) *standardDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s standardDo) LeftJoin(table schema.Tabler, on ...field.Expr) *standardDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s standardDo) RightJoin(table schema.Tabler, on ...field.Expr) *standardDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s standardDo) Group(cols ...field.Expr) *standardDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s standardDo) Having(conds ...gen.Condition) *standardDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s standardDo) Limit(limit int) *standardDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s standardDo) Offset(offset int) *standardDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s standardDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *standardDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s standardDo) Unscoped() *standardDo {
	return s.withDO(s.DO.Unscoped())
}

func (s standardDo) Create(values ...*model.Standard) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s standardDo) CreateInBatches(values []*model.Standard, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s standardDo) Save(values ...*model.Standard) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s standardDo) First() (*model.Standard, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Standard), nil
	}
}

func (s standardDo) Take() (*model.Standard, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Standard), nil
	}
}

func (s standardDo) Last() (*model.Standard, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Standard), nil
	}
}

func (s standardDo) Find() ([]*model.Standard, error) {
	result, err := s.DO.Find()
	return result.([]*model.Standard), err
}

func (s standardDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Standard, err error) {
	buf := make([]*model.Standard, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s standardDo) FindInBatches(result *[]*model.Standard, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s standardDo) Attrs(attrs ...field.AssignExpr) *standardDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s standardDo) Assign(attrs ...field.AssignExpr) *standardDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s standardDo) Joins(fields ...field.RelationField) *standardDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s standardDo) Preload(fields ...field.RelationField) *standardDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s standardDo) FirstOrInit() (*model.Standard, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Standard), nil
	}
}

func (s standardDo) FirstOrCreate() (*model.Standard, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Standard), nil
	}
}

func (s standardDo) FindByPage(offset int, limit int) (result []*model.Standard, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s standardDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s *standardDo) withDO(do gen.Dao) *standardDo {
	s.DO = *do.(*gen.DO)
	return s
}
