// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/info": {
            "get": {
                "description": "获取管理员信息",
                "tags": [
                    "admin"
                ],
                "summary": "管理员信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Admin"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/admin/login/{code}": {
            "post": {
                "description": "管理员登录",
                "tags": [
                    "admin"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "oauth2 code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mid.Admin"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    }
                }
            }
        },
        "/api/admin/public/{group}": {
            "get": {
                "description": "获取特定组别的面试时间",
                "tags": [
                    "public"
                ],
                "summary": "获取面试时间",
                "parameters": [
                    {
                        "enum": [
                            "机械",
                            "电控",
                            "视觉"
                        ],
                        "type": "string",
                        "description": "组别",
                        "name": "group",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.OptionalTime"
                        }
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/admin/public/{key}": {
            "get": {
                "description": "可获取\"form\", \"announce\", \"time-frame\"",
                "tags": [
                    "public",
                    "setting"
                ],
                "summary": "获取设置",
                "parameters": [
                    {
                        "enum": [
                            "form",
                            "announce",
                            "time-frame"
                        ],
                        "type": "string",
                        "description": "获取设置的键",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/admin/remark/{id}": {
            "get": {
                "description": "获取我对特定面试者的评价",
                "tags": [
                    "admin"
                ],
                "summary": "获取评价",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "面试者id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Remark"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "put": {
                "description": "设置我对特定面试者的评价",
                "tags": [
                    "admin"
                ],
                "summary": "设置评价",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "面试者id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "评价",
                        "name": "remark",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Remark"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "401": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/admin/standard": {
            "put": {
                "description": "设置默认评价标准",
                "tags": [
                    "admin"
                ],
                "summary": "设置默认标准",
                "parameters": [
                    {
                        "description": "评价标准的ID",
                        "name": "Standard",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrl.standard"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": ""
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/applicant/info": {
            "get": {
                "description": "面试者获取自己的微信信息",
                "tags": [
                    "applicant"
                ],
                "summary": "面试者微信信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mid.Applicant"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/applicant/login/{token}": {
            "post": {
                "description": "面试者登录",
                "tags": [
                    "applicant"
                ],
                "summary": "面试者登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "oauth2 token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mid.Applicant"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    }
                }
            }
        },
        "/api/setting/announce": {
            "put": {
                "description": "修改公告设置",
                "tags": [
                    "admin",
                    "setting"
                ],
                "summary": "设置公告",
                "parameters": [
                    {
                        "description": "公告",
                        "name": "announce",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrl.announce"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": ""
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/setting/form": {
            "put": {
                "description": "修改报名表设置",
                "tags": [
                    "admin",
                    "setting"
                ],
                "summary": "设置报名表",
                "parameters": [
                    {
                        "description": "报名表",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrl.form"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": ""
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/setting/time-frame": {
            "put": {
                "description": "修改时间节点设置",
                "tags": [
                    "admin",
                    "setting"
                ],
                "summary": "设置时间节点",
                "parameters": [
                    {
                        "description": "时间节点",
                        "name": "timeframe",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ctrl.timeframe"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": ""
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "ctrl.announce": {
            "type": "object",
            "properties": {
                "admitted": {
                    "type": "string"
                },
                "failed": {
                    "type": "string"
                },
                "haventAppliedForm": {
                    "type": "string"
                },
                "haventInterview": {
                    "type": "string"
                },
                "haventSelectedTime": {
                    "type": "string"
                },
                "interviewed": {
                    "type": "string"
                }
            }
        },
        "ctrl.field": {
            "type": "object",
            "required": [
                "key",
                "name",
                "regexp",
                "required",
                "type"
            ],
            "properties": {
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "option": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "regexp": {
                    "type": "string"
                },
                "required": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "ctrl.form": {
            "type": "object",
            "required": [
                "fields",
                "intent"
            ],
            "properties": {
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ctrl.field"
                    }
                },
                "intent": {
                    "$ref": "#/definitions/ctrl.intent"
                }
            }
        },
        "ctrl.intent": {
            "type": "object",
            "required": [
                "max",
                "min",
                "parallel"
            ],
            "properties": {
                "max": {
                    "type": "integer"
                },
                "min": {
                    "type": "integer"
                },
                "parallel": {
                    "type": "boolean"
                }
            }
        },
        "ctrl.standard": {
            "type": "object",
            "required": [
                "standard_id"
            ],
            "properties": {
                "standard_id": {
                    "type": "integer"
                }
            }
        },
        "ctrl.timeframe": {
            "type": "object",
            "required": [
                "done",
                "form-end",
                "form-start",
                "time-end",
                "time-start"
            ],
            "properties": {
                "done": {
                    "type": "string"
                },
                "form-end": {
                    "type": "string"
                },
                "form-start": {
                    "type": "string"
                },
                "time-end": {
                    "type": "string"
                },
                "time-start": {
                    "type": "string"
                }
            }
        },
        "mid.Admin": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mid.Group"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "mid.Applicant": {
            "type": "object",
            "properties": {
                "headimgurl": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "openid": {
                    "type": "string"
                }
            }
        },
        "mid.Group": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "model.Admin": {
            "type": "object",
            "properties": {
                "standard_id": {
                    "type": "integer"
                }
            }
        },
        "model.OptionalTime": {
            "type": "object",
            "properties": {
                "group": {
                    "type": "string"
                },
                "intentRank": {
                    "description": "限定面试轮次",
                    "type": "integer"
                },
                "theDate": {
                    "type": "string"
                },
                "theLocation": {
                    "type": "string"
                },
                "theTime": {
                    "type": "string"
                }
            }
        },
        "model.Question": {
            "type": "object",
            "properties": {
                "group": {
                    "type": "string"
                },
                "theQuestion": {
                    "type": "string"
                }
            }
        },
        "model.Remark": {
            "type": "object",
            "properties": {
                "remark": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
