definitions:
  ctrl.announce:
    properties:
      admitted:
        type: string
      failed:
        type: string
      haventAppliedForm:
        type: string
      haventInterview:
        type: string
      haventSelectedTime:
        type: string
      interviewed:
        type: string
    type: object
  ctrl.field:
    properties:
      key:
        type: string
      name:
        type: string
      option:
        items:
          type: string
        type: array
      regexp:
        type: string
      required:
        type: boolean
      type:
        type: string
    required:
    - key
    - name
    - regexp
    - required
    - type
    type: object
  ctrl.form:
    properties:
      fields:
        items:
          $ref: '#/definitions/ctrl.field'
        type: array
      intent:
        $ref: '#/definitions/ctrl.intent'
    required:
    - fields
    - intent
    type: object
  ctrl.intent:
    properties:
      max:
        type: integer
      min:
        type: integer
      parallel:
        type: boolean
    required:
    - max
    - min
    - parallel
    type: object
  ctrl.timeframe:
    properties:
      done:
        type: string
      form-end:
        type: string
      form-start:
        type: string
      time-end:
        type: string
      time-start:
        type: string
    required:
    - done
    - form-end
    - form-start
    - time-end
    - time-start
    type: object
  mid.Admin:
    properties:
      avatar:
        type: string
      groups:
        items:
          $ref: '#/definitions/mid.Group'
        type: array
      id:
        type: integer
      name:
        type: string
    type: object
  mid.Applicant:
    properties:
      headimgurl:
        type: string
      nickname:
        type: string
      openid:
        type: string
    type: object
  mid.Group:
    properties:
      name:
        type: string
    type: object
  model.Admin:
    properties:
      standard_id:
        type: integer
    type: object
  model.Admit:
    properties:
      applicantID:
        type: integer
      group:
        type: string
    type: object
  model.Applicant:
    properties:
      avatar:
        type: string
      form:
        type: string
      gender:
        type: boolean
      intents:
        items:
          $ref: '#/definitions/model.Intent'
        type: array
      name:
        type: string
      phone:
        type: string
    type: object
  model.Intent:
    properties:
      applicant:
        $ref: '#/definitions/model.Applicant'
      applicantID:
        type: integer
      group:
        type: string
      intentRank:
        description: nil 为平行志愿
        type: integer
      optionalTime:
        $ref: '#/definitions/model.OptionalTime'
      optionalTimeID:
        type: integer
    type: object
  model.OptionalTime:
    properties:
      group:
        type: string
      intentRank:
        description: 限定面试轮次
        type: integer
      theDate:
        type: string
      theLocation:
        type: string
      theTime:
        type: string
    type: object
  model.Question:
    properties:
      group:
        type: string
      question:
        type: string
    type: object
  model.Remark:
    properties:
      applicantID:
        type: integer
      theRemark:
        type: string
    type: object
  model.Score:
    properties:
      adminID:
        type: integer
      applicantID:
        type: integer
      evaluationDetails:
        type: string
      group:
        type: string
      score:
        type: number
      standardID:
        type: integer
      updatedAt:
        type: string
    type: object
  model.Standard:
    properties:
      adminID:
        description: 上次修改的管理员
        type: integer
      content:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/admin/admit:
    delete:
      description: 管理员录取/取消录取面试者到特定组别
      parameters:
      - description: 录取
        in: body
        name: admit
        required: true
        schema:
          $ref: '#/definitions/model.Admit'
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 录取/取消录取
      tags:
      - admin
    put:
      description: 管理员录取/取消录取面试者到特定组别
      parameters:
      - description: 录取
        in: body
        name: admit
        required: true
        schema:
          $ref: '#/definitions/model.Admit'
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 录取/取消录取
      tags:
      - admin
  /api/admin/applicant/{id}:
    get:
      description: 管理员获取面试者信息
      parameters:
      - description: 面试者ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Applicant'
        "401":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: 面试者信息
      tags:
      - admin
  /api/admin/info:
    get:
      description: 获取管理员信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mid.Admin'
        "401":
          description: ""
        "500":
          description: ""
      summary: 管理员信息
      tags:
      - admin
  /api/admin/login/:
    post:
      description: 管理员登录
      parameters:
      - description: oauth2 code
        in: path
        name: code
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mid.Admin'
        "401":
          description: ""
        "404":
          description: ""
      summary: 管理员登录
      tags:
      - admin
  /api/admin/public/{key}:
    get:
      description: 可获取"form", "announce", "time-frame"
      parameters:
      - description: 获取设置的键
        enum:
        - form
        - announce
        - time-frame
        in: path
        name: key
        required: true
        type: string
      responses:
        "200":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: 获取设置
      tags:
      - public
      - setting
  /api/admin/public/exam/:
    get:
      description: 获取特定组别的面试题库
      parameters:
      - description: 组别
        enum:
        - 机械
        - 电控
        - 视觉
        in: path
        name: group
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Question'
        "404":
          description: ""
        "500":
          description: ""
      summary: 获取面试题库
      tags:
      - public
  /api/admin/public/time/:
    get:
      description: 获取特定组别的面试时间
      parameters:
      - description: 组别
        enum:
        - 机械
        - 电控
        - 视觉
        in: path
        name: group
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OptionalTime'
        "404":
          description: ""
        "500":
          description: ""
      summary: 获取面试时间
      tags:
      - public
  /api/admin/question:
    post:
      description: 管理员添加面试题目
      parameters:
      - description: 题目
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/model.Question'
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 添加题目
      tags:
      - admin
  /api/admin/question/{id}:
    delete:
      description: 管理员删除面试题目
      parameters:
      - description: 题目ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 删除题目
      tags:
      - admin
    put:
      description: 管理员修改面试题目
      parameters:
      - description: 题目ID
        in: path
        name: id
        required: true
        type: integer
      - description: 题目，仅question本身，其他内容将被忽略
        in: body
        name: question
        required: true
        schema:
          type: string
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 修改题目
      tags:
      - admin
  /api/admin/remark/{id}:
    get:
      description: 管理员获取对特定面试者的评价
      parameters:
      - description: 面试者ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.Remark'
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 获取评价
      tags:
      - admin
    put:
      description: 管理员修改对特定面试者的评价
      parameters:
      - description: 面试者ID
        in: path
        name: id
        required: true
        type: integer
      - description: 评价，仅remark本身，其他内容将被忽略
        in: body
        name: remark
        required: true
        schema:
          $ref: '#/definitions/model.Remark'
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 修改评价
      tags:
      - admin
  /api/admin/score:
    delete:
      description: 管理员删除面试者分数
      parameters:
      - description: 分数
        in: body
        name: score
        required: true
        schema:
          $ref: '#/definitions/model.Score'
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 删除分数
      tags:
      - admin
  /api/admin/score/{id}:
    get:
      description: 管理员获取面试者分数
      parameters:
      - description: 面试者ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Score'
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 获取分数
      tags:
      - admin
  /api/admin/standard:
    get:
      description: 管理员获取所有评价标准
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Standard'
            type: array
        "401":
          description: ""
        "500":
          description: ""
      summary: 所有标准
      tags:
      - admin
    post:
      description: 管理员添加评价标准
      parameters:
      - description: 标准
        in: body
        name: standard
        required: true
        schema:
          $ref: '#/definitions/model.Standard'
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 添加标准
      tags:
      - admin
    put:
      description: 设置默认评价标准
      parameters:
      - description: 仅选取评价标准的ID
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/model.Admin'
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 设置默认标准
      tags:
      - admin
  /api/admin/standard/{id}:
    delete:
      description: 管理员删除特定评价标准
      parameters:
      - description: 评价标准ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 删除标准
      tags:
      - admin
    get:
      description: 管理员获取特定评价标准
      parameters:
      - description: 评价标准ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Standard'
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 单个标准
      tags:
      - admin
    put:
      description: 管理员更新特定评价标准
      parameters:
      - description: 评价标准ID
        in: path
        name: id
        required: true
        type: integer
      - description: 标准
        in: body
        name: standard
        required: true
        schema:
          $ref: '#/definitions/model.Standard'
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 更新标准
      tags:
      - admin
  /api/admin/time/{group}:
    put:
      consumes:
      - multipart/form-data
      description: 管理员上传面试时间csv文件
      parameters:
      - description: 组
        in: path
        name: group
        required: true
        type: string
      - description: csv 文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "204":
          description: ""
      summary: 设置面试时间文件
      tags:
      - admin
  /api/applicant/info:
    get:
      description: 面试者获取自己的微信信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mid.Applicant'
        "401":
          description: ""
        "500":
          description: ""
      summary: 面试者微信信息
      tags:
      - applicant
  /api/applicant/login/:
    post:
      description: 面试者登录
      parameters:
      - description: oauth2 token
        in: path
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mid.Applicant'
        "401":
          description: ""
        "404":
          description: ""
      summary: 面试者登录
      tags:
      - applicant
  /api/setting/announce:
    put:
      description: 修改公告设置
      parameters:
      - description: 公告
        in: body
        name: announce
        required: true
        schema:
          $ref: '#/definitions/ctrl.announce'
      responses:
        "200":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 设置公告
      tags:
      - admin
      - setting
  /api/setting/form:
    put:
      description: 修改报名表设置
      parameters:
      - description: 报名表
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/ctrl.form'
      responses:
        "200":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 设置报名表
      tags:
      - admin
      - setting
  /api/setting/time-frame:
    put:
      description: 修改时间节点设置
      parameters:
      - description: 时间节点
        in: body
        name: timeframe
        required: true
        schema:
          $ref: '#/definitions/ctrl.timeframe'
      responses:
        "200":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 设置时间节点
      tags:
      - admin
      - setting
swagger: "2.0"
