definitions:
  ctrl.standard:
    properties:
      standard_id:
        type: integer
    required:
    - standard_id
    type: object
  mid.Admin:
    properties:
      avatar:
        type: string
      groups:
        items:
          $ref: '#/definitions/mid.Group'
        type: array
      id:
        type: integer
      name:
        type: string
    type: object
  mid.Applicant:
    properties:
      headimgurl:
        type: string
      nickname:
        type: string
      openid:
        type: string
    type: object
  mid.Group:
    properties:
      name:
        type: string
    type: object
  model.Admin:
    properties:
      id:
        type: integer
      name:
        type: string
      standard:
        $ref: '#/definitions/model.Standard'
      standardID:
        type: integer
    type: object
  model.Standard:
    properties:
      adminID:
        description: 上次修改的管理员
        type: integer
      content:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/admin/info:
    get:
      description: 获取管理员信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Admin'
        "401":
          description: ""
        "500":
          description: ""
      summary: 管理员信息
      tags:
      - admin
  /api/admin/login/{code}:
    post:
      description: 管理员登录
      parameters:
      - description: oauth2 code
        in: path
        name: code
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mid.Admin'
        "401":
          description: ""
        "404":
          description: ""
      summary: 管理员登录
      tags:
      - admin
  /api/admin/standard:
    put:
      description: 设置默认评价标准
      parameters:
      - description: 评价标准的ID
        in: body
        name: Standard
        required: true
        schema:
          $ref: '#/definitions/ctrl.standard'
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "401":
          description: ""
        "500":
          description: ""
      summary: 设置默认标准
      tags:
      - admin
  /api/applicant/login/{token}:
    post:
      description: 面试者登录
      parameters:
      - description: oauth2 token
        in: path
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mid.Applicant'
        "401":
          description: ""
        "404":
          description: ""
      summary: 面试者登录
      tags:
      - applicant
  /api/public/{key}:
    get:
      description: 可获取"form", "announce", "time-frame"
      parameters:
      - description: 获取设置的键
        enum:
        - form
        - announce
        - time-frame
        in: path
        name: key
        required: true
        type: string
      responses:
        "200":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: 获取设置
      tags:
      - public
swagger: "2.0"
